# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1366, 768)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 708))
        MainWindow.setMaximumSize(QtCore.QSize(1366, 768))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        MainWindow.setFont(font)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.France))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setMaximumSize(QtCore.QSize(1366, 768))
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 0, 1351, 701))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setMinimumSize(QtCore.QSize(960, 480))
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 1, 0, 1, 2)
        self.ControlPanel = QtWidgets.QWidget(self.gridLayoutWidget)
        self.ControlPanel.setObjectName("ControlPanel")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.ControlPanel)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setHorizontalSpacing(4)
        self.gridLayout_3.setVerticalSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.armUpButton = QtWidgets.QPushButton(self.ControlPanel)
        self.armUpButton.setMinimumSize(QtCore.QSize(0, 50))
        self.armUpButton.setObjectName("armUpButton")
        self.verticalLayout_5.addWidget(self.armUpButton)
        self.armDownButton = QtWidgets.QPushButton(self.ControlPanel)
        self.armDownButton.setMinimumSize(QtCore.QSize(0, 50))
        self.armDownButton.setObjectName("armDownButton")
        self.verticalLayout_5.addWidget(self.armDownButton)
        self.gridLayout_3.addLayout(self.verticalLayout_5, 2, 1, 2, 1)
        self.label_2 = QtWidgets.QLabel(self.ControlPanel)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.ControlPanel)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 2, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.clampOpenButton = QtWidgets.QPushButton(self.ControlPanel)
        self.clampOpenButton.setMinimumSize(QtCore.QSize(0, 50))
        self.clampOpenButton.setObjectName("clampOpenButton")
        self.verticalLayout_4.addWidget(self.clampOpenButton)
        self.clampCloseButton = QtWidgets.QPushButton(self.ControlPanel)
        self.clampCloseButton.setMinimumSize(QtCore.QSize(0, 50))
        self.clampCloseButton.setObjectName("clampCloseButton")
        self.verticalLayout_4.addWidget(self.clampCloseButton)
        self.gridLayout_3.addLayout(self.verticalLayout_4, 2, 2, 2, 1)
        self.line_6 = QtWidgets.QFrame(self.ControlPanel)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_3.addWidget(self.line_6, 1, 1, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout_3, 2, 5, 4, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.chRightFwButton = QtWidgets.QPushButton(self.ControlPanel)
        self.chRightFwButton.setMinimumSize(QtCore.QSize(0, 50))
        self.chRightFwButton.setObjectName("chRightFwButton")
        self.verticalLayout_3.addWidget(self.chRightFwButton)
        self.chRightBackButton = QtWidgets.QPushButton(self.ControlPanel)
        self.chRightBackButton.setMinimumSize(QtCore.QSize(0, 50))
        self.chRightBackButton.setObjectName("chRightBackButton")
        self.verticalLayout_3.addWidget(self.chRightBackButton)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 4, 3, 2, 1)
        self.label = QtWidgets.QLabel(self.ControlPanel)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.ControlPanel)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 3, 3, 1, 1)
        self.line = QtWidgets.QFrame(self.ControlPanel)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 3, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.ControlPanel)
        self.line_3.setLineWidth(1)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_2.addWidget(self.line_3, 2, 1, 4, 1)
        self.label_3 = QtWidgets.QLabel(self.ControlPanel)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 3, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.chLeftFwButton = QtWidgets.QPushButton(self.ControlPanel)
        self.chLeftFwButton.setMinimumSize(QtCore.QSize(0, 50))
        self.chLeftFwButton.setObjectName("chLeftFwButton")
        self.verticalLayout_2.addWidget(self.chLeftFwButton)
        self.chLeftBackButton = QtWidgets.QPushButton(self.ControlPanel)
        self.chLeftBackButton.setMinimumSize(QtCore.QSize(0, 50))
        self.chLeftBackButton.setObjectName("chLeftBackButton")
        self.verticalLayout_2.addWidget(self.chLeftBackButton)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 4, 0, 2, 1)
        self.line_5 = QtWidgets.QFrame(self.ControlPanel)
        self.line_5.setLineWidth(1)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_2.addWidget(self.line_5, 2, 4, 4, 1)
        self.gridLayout.addWidget(self.ControlPanel, 2, 0, 1, 2)
        self.ConfigurationPanel = QtWidgets.QWidget(self.gridLayoutWidget)
        self.ConfigurationPanel.setObjectName("ConfigurationPanel")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.ConfigurationPanel)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.startGameButton = QtWidgets.QPushButton(self.ConfigurationPanel)
        self.startGameButton.setMinimumSize(QtCore.QSize(0, 50))
        self.startGameButton.setObjectName("startGameButton")
        self.verticalLayout.addWidget(self.startGameButton)
        self.configButton = QtWidgets.QPushButton(self.ConfigurationPanel)
        self.configButton.setMinimumSize(QtCore.QSize(0, 50))
        self.configButton.setObjectName("configButton")
        self.verticalLayout.addWidget(self.configButton)
        self.stopResetButton = QtWidgets.QPushButton(self.ConfigurationPanel)
        self.stopResetButton.setMinimumSize(QtCore.QSize(0, 50))
        self.stopResetButton.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.France))
        self.stopResetButton.setObjectName("stopResetButton")
        self.verticalLayout.addWidget(self.stopResetButton)
        self.frame = QtWidgets.QFrame(self.ConfigurationPanel)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.timeLeftLabel = QtWidgets.QLabel(self.frame)
        self.timeLeftLabel.setGeometry(QtCore.QRect(95, 10, 241, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.timeLeftLabel.setFont(font)
        self.timeLeftLabel.setScaledContents(True)
        self.timeLeftLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.timeLeftLabel.setObjectName("timeLeftLabel")
        self.timeLeftLcd = QtWidgets.QLCDNumber(self.frame)
        self.timeLeftLcd.setGeometry(QtCore.QRect(10, 40, 330, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeLeftLcd.sizePolicy().hasHeightForWidth())
        self.timeLeftLcd.setSizePolicy(sizePolicy)
        self.timeLeftLcd.setMinimumSize(QtCore.QSize(330, 100))
        self.timeLeftLcd.setMaximumSize(QtCore.QSize(330, 100))
        self.timeLeftLcd.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.France))
        self.timeLeftLcd.setObjectName("timeLeftLcd")
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.ConfigurationPanel)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.timeLeftLabel_2 = QtWidgets.QLabel(self.frame_2)
        self.timeLeftLabel_2.setGeometry(QtCore.QRect(90, 10, 241, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.timeLeftLabel_2.setFont(font)
        self.timeLeftLabel_2.setScaledContents(True)
        self.timeLeftLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.timeLeftLabel_2.setObjectName("timeLeftLabel_2")
        self.distanceLcd = QtWidgets.QLCDNumber(self.frame_2)
        self.distanceLcd.setGeometry(QtCore.QRect(10, 30, 330, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.distanceLcd.sizePolicy().hasHeightForWidth())
        self.distanceLcd.setSizePolicy(sizePolicy)
        self.distanceLcd.setMinimumSize(QtCore.QSize(330, 100))
        self.distanceLcd.setMaximumSize(QtCore.QSize(330, 100))
        self.distanceLcd.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.France))
        self.distanceLcd.setObjectName("distanceLcd")
        self.verticalLayout.addWidget(self.frame_2)
        self.gridLayout.addWidget(self.ConfigurationPanel, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1366, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuRobot_Killer = QtWidgets.QMenu(self.menuBar)
        self.menuRobot_Killer.setObjectName("menuRobot_Killer")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar.addAction(self.menuRobot_Killer.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Robot Killer App v0.9"))
        self.armUpButton.setText(_translate("MainWindow", "Bras UP (↑)"))
        self.armDownButton.setText(_translate("MainWindow", "Bras DOWN (↓)"))
        self.label_2.setText(_translate("MainWindow", "Bras Robot"))
        self.label_4.setText(_translate("MainWindow", "Pince du bras"))
        self.clampOpenButton.setText(_translate("MainWindow", "Pince OPEN (←)"))
        self.clampCloseButton.setText(_translate("MainWindow", "Pince CLOSE (→)"))
        self.chRightFwButton.setText(_translate("MainWindow", "Avancer (Maj Droit)"))
        self.chRightBackButton.setText(_translate("MainWindow", "Reculer (Ctrl Droit)"))
        self.label.setText(_translate("MainWindow", "Chenille Gauche"))
        self.label_3.setText(_translate("MainWindow", "Chenille droite"))
        self.chLeftFwButton.setText(_translate("MainWindow", "Avancer (Maj Gauche)"))
        self.chLeftBackButton.setText(_translate("MainWindow", "Reculer (Ctrl Gauche)"))
        self.startGameButton.setText(_translate("MainWindow", "Start Game"))
        self.configButton.setText(_translate("MainWindow", "Configuration"))
        self.stopResetButton.setText(_translate("MainWindow", "Arret / RAZ compteurs"))
        self.timeLeftLabel.setText(_translate("MainWindow", "Temps de jeu restent"))
        self.timeLeftLabel_2.setText(_translate("MainWindow", "Distance collision"))
        self.menuRobot_Killer.setTitle(_translate("MainWindow", "Robot Killer App"))

