# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1024, 768)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 768))
        MainWindow.setMaximumSize(QtCore.QSize(1024, 768))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        MainWindow.setFont(font)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.France))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setMaximumSize(QtCore.QSize(1024, 768))
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 0, 1011, 701))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.ConfigurationPanel = QtWidgets.QWidget(self.gridLayoutWidget)
        self.ConfigurationPanel.setObjectName("ConfigurationPanel")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.ConfigurationPanel)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.startGameButton = QtWidgets.QPushButton(self.ConfigurationPanel)
        self.startGameButton.setMinimumSize(QtCore.QSize(0, 50))
        self.startGameButton.setObjectName("startGameButton")
        self.verticalLayout.addWidget(self.startGameButton)
        self.configButton = QtWidgets.QPushButton(self.ConfigurationPanel)
        self.configButton.setMinimumSize(QtCore.QSize(0, 50))
        self.configButton.setObjectName("configButton")
        self.verticalLayout.addWidget(self.configButton)
        self.stopResetButton = QtWidgets.QPushButton(self.ConfigurationPanel)
        self.stopResetButton.setMinimumSize(QtCore.QSize(0, 50))
        self.stopResetButton.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.France))
        self.stopResetButton.setObjectName("stopResetButton")
        self.verticalLayout.addWidget(self.stopResetButton)
        self.frame = QtWidgets.QFrame(self.ConfigurationPanel)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.timeLeftLabel = QtWidgets.QLabel(self.frame)
        self.timeLeftLabel.setGeometry(QtCore.QRect(95, 10, 241, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.timeLeftLabel.setFont(font)
        self.timeLeftLabel.setScaledContents(True)
        self.timeLeftLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.timeLeftLabel.setObjectName("timeLeftLabel")
        self.timeLeftLcd = QtWidgets.QLCDNumber(self.frame)
        self.timeLeftLcd.setGeometry(QtCore.QRect(5, 40, 330, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeLeftLcd.sizePolicy().hasHeightForWidth())
        self.timeLeftLcd.setSizePolicy(sizePolicy)
        self.timeLeftLcd.setMinimumSize(QtCore.QSize(330, 100))
        self.timeLeftLcd.setMaximumSize(QtCore.QSize(330, 100))
        self.timeLeftLcd.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.France))
        self.timeLeftLcd.setObjectName("timeLeftLcd")
        self.verticalLayout.addWidget(self.frame)
        self.gridLayout.addWidget(self.ConfigurationPanel, 0, 1, 1, 1)
        self.graphicsView = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setMinimumSize(QtCore.QSize(640, 480))
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.ControlPanel = QtWidgets.QWidget(self.gridLayoutWidget)
        self.ControlPanel.setObjectName("ControlPanel")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.ControlPanel)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.line = QtWidgets.QFrame(self.ControlPanel)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 3, 0, 1, 1)
        self.mvLeftButton = QtWidgets.QPushButton(self.ControlPanel)
        self.mvLeftButton.setMinimumSize(QtCore.QSize(0, 50))
        self.mvLeftButton.setObjectName("mvLeftButton")
        self.gridLayout_2.addWidget(self.mvLeftButton, 5, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.ControlPanel)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 1)
        self.mvRightButton = QtWidgets.QPushButton(self.ControlPanel)
        self.mvRightButton.setMinimumSize(QtCore.QSize(0, 50))
        self.mvRightButton.setObjectName("mvRightButton")
        self.gridLayout_2.addWidget(self.mvRightButton, 5, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.ControlPanel)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 2, 1, 3)
        self.mvForwardButton = QtWidgets.QPushButton(self.ControlPanel)
        self.mvForwardButton.setMinimumSize(QtCore.QSize(0, 50))
        self.mvForwardButton.setObjectName("mvForwardButton")
        self.gridLayout_2.addWidget(self.mvForwardButton, 4, 3, 1, 1)
        self.mvBackButton = QtWidgets.QPushButton(self.ControlPanel)
        self.mvBackButton.setMinimumSize(QtCore.QSize(0, 50))
        self.mvBackButton.setObjectName("mvBackButton")
        self.gridLayout_2.addWidget(self.mvBackButton, 5, 3, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.chFwButton = QtWidgets.QPushButton(self.ControlPanel)
        self.chFwButton.setMinimumSize(QtCore.QSize(0, 50))
        self.chFwButton.setObjectName("chFwButton")
        self.verticalLayout_2.addWidget(self.chFwButton)
        self.chBackButton = QtWidgets.QPushButton(self.ControlPanel)
        self.chBackButton.setMinimumSize(QtCore.QSize(0, 50))
        self.chBackButton.setObjectName("chBackButton")
        self.verticalLayout_2.addWidget(self.chBackButton)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 4, 0, 2, 1)
        self.line_2 = QtWidgets.QFrame(self.ControlPanel)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 3, 2, 1, 3)
        self.line_3 = QtWidgets.QFrame(self.ControlPanel)
        self.line_3.setLineWidth(1)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_2.addWidget(self.line_3, 2, 1, 4, 1)
        self.gridLayout.addWidget(self.ControlPanel, 2, 0, 1, 2)
        self.line_4 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1024, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuRobot_Killer = QtWidgets.QMenu(self.menuBar)
        self.menuRobot_Killer.setObjectName("menuRobot_Killer")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar.addAction(self.menuRobot_Killer.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Robot Killer App v0.9"))
        self.startGameButton.setText(_translate("MainWindow", "Start Game"))
        self.configButton.setText(_translate("MainWindow", "Configuration"))
        self.stopResetButton.setText(_translate("MainWindow", "Arret / RAZ compteurs"))
        self.timeLeftLabel.setText(_translate("MainWindow", "Temps de jeu restent"))
        self.mvLeftButton.setText(_translate("MainWindow", "Tourner a gauche (←)"))
        self.label.setText(_translate("MainWindow", "Control des chenilles"))
        self.mvRightButton.setText(_translate("MainWindow", "Tourner a droite (→)"))
        self.label_2.setText(_translate("MainWindow", "Control de Jeu"))
        self.mvForwardButton.setText(_translate("MainWindow", "Avancer (↑)"))
        self.mvBackButton.setText(_translate("MainWindow", "Reculer (↓)"))
        self.chFwButton.setText(_translate("MainWindow", "Avant (W)"))
        self.chBackButton.setText(_translate("MainWindow", "Arriere (S)"))
        self.menuRobot_Killer.setTitle(_translate("MainWindow", "Robot Killer App"))

